<div class="container">
	<h2>Bienvenue sur le site du mec qui fait tout le temps les même headers..</h2>
	<img src="public/images/pano.jpg" alt="essuie-tout">
	<h3 class="h-home">Lorem Ipsuretre</h3>
	<p class="p-home">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias minima facilis, pariatur dignissimos earum eius, exercitationem aut aspernatur ratione quo numquam qui, quam corrupti, quaerat ipsa iusto corporis molestias ipsam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam illo repellat asperiores dolorem blanditiis harum quod pariatur modi consectetur itaque debitis, quae nesciunt dolores rem suscipit. Aliquid odio laboriosam, impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id non, ut. Cupiditate quisquam ad suscipit dolorum et, voluptatem, itaque voluptates. Laboriosam quo in expedita dolorem inventore doloribus minus deserunt at.
	</p>
	<br>
	<p class="p-home">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi eligendi, ea tempore qui in eaque quidem alias voluptatibus minus doloremque, veniam placeat ipsum. Inventore dolores neque, itaque aspernatur aut amet. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores optio unde quod. Non quasi quis perferendis rem excepturi iusto est numquam at, fugit distinctio ut necessitatibus, animi sapiente? Eum, dolores.
	</p>
	<img src="public/images/wallpaper.jpg" alt="saucisson" class="wallpap">	
	<p class="p-home last-p">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias minima facilis, pariatur dignissimos earum eius, exercitationem aut aspernatur ratione quo numquam qui, quam corrupti, quaerat ipsa iusto corporis molestias ipsam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam illo repellat asperiores dolorem blanditiis harum quod pariatur modi consectetur itaque debitis, quae nesciunt dolores rem suscipit. Aliquid odio laboriosam, impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id non, ut. Cupiditate quisquam ad suscipit dolorum et, voluptatem, itaque voluptates. Laboriosam quo in expedita dolorem inventore doloribus minus deserunt at.
	</p>
	<br>
	<p class="p-home clearfix">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias minima facilis, pariatur dignissimos earum eius, exercitationem aut aspernatur ratione quo numquam qui, quam corrupti, quaerat ipsa iusto corporis molestias ipsam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam illo repellat asperiores dolorem blanditiis harum quod pariatur modi consectetur itaque debitis, quae nesciunt dolores rem suscipit. Aliquid odio laboriosam, impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id non, ut. Cupiditate quisquam ad suscipit dolorum et, voluptatem, itaque voluptates. Laboriosam quo in expedita dolorem inventore doloribus minus deserunt at. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae velit iusto ea illo, impedit nulla nobis nemo quia! Iure veritatis ut necessitatibus magnam repellendus consequatur laboriosam? Veritatis neque, quam rem.
	</p>		
</div>