<div class="container-login">
	<h2 class="h-log">Se connecter</h2>
	<form method="POST" class="log-form">
		<label class="customLabel" for="name">Login :</label>
		<input class="input-log" type="text" name="name" id="name"><br>
		<label class="customLabel" for="pwd">Mot de passe :</label>
		<input class="input-log" type="password" name="pwd" id="pwd"><br>
		<div class="clearfix"></div>
		<button class="new-btn" type="submit">Entrer</button>
	</form>
</div>