<div class="container-login">
	<h2 class="h-log">Créer un compte :</h2>
	<form method="POST" class="log-form">
		<label class="customLabel" for="name">Login :</label>
		<input class="input-log" type="text" name="name" id="name"><br>

		<label class="customLabel" for="pwd">Mot de passe :</label>
		<input class="input-log" type="password" name="pwd" id="pwd"><br>

		<label class="customLabel" for="pwd">Confirmer mdp :</label>
		<input class="input-log" type="password" name="pwd2" id="pwd2"><br>

		<label class="customLabel" for="pwd">Addresse mail :</label>
		<input class="input-log" type="email" name="email" id="email"><br>

		<label class="customLabel" for="pwd">Date de naissance :</label>
		<input class="input-log" type="text" name="date" id="date"><br>
		
		<div class="clearfix"></div>
		<button class="new-btn" type="submit">Entrer</button>
	</form>
</div>