<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>projet_link</title>
	<link href="https://fonts.googleapis.com/css?family=Baloo+Paaji|Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="public/styles/reset.css">
	<link rel="stylesheet" type="text/css" href="public/styles/style.css">
</head>
<body>
	<?php
	require 'apps/header.php';
	require 'apps/content.php';
	require 'apps/footer.php';
	?>
</body>
</html>